before:
  hooks:
    - go mod download
builds:
- main: ./main.go
  id: check_dns_cloudflare
  binary: check_dns_cloudflare
  goos:
    - linux
    - windows
    - darwin
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
